### ISSUE TITLE
[bug] shortcut for Next not working

### ISSUE THREAD

**Issue by ObeyYourHeart** [bjsi/incremental-everything#29]
1. I've tried using Ctrl+/ to input 'next repetition' but it's still not working. The shortcut key is also not functioning.
2. I don't want to have to use Ctrl, Alt or Shift for keyboard shortcuts; I'd prefer to be able to use keys like F7 directly. If this can't be achieved, then perhaps I could do it through a script.
![录制_2023_09_03_03_35_55_765](https://github.com/bjsi/incremental-everything/assets/114028910/0694dc17-0b98-4d71-aa1c-9817f16f0e21)

**Comment by bjsi** [comment]
fixed

**Comment by ObeyYourHeart** [comment]
It still doesn't work, I'm using Win11. I've tried both the web version (Edge) and the desktop version of RemNote. The version I'm using is 1-12-25, and 1-12-28 also doesn't work on betaremnote.com.
This applies to both shortcuts and commands.
